version: "3"

services:
  kali:
    build: .
    network_mode: host
    privileged: true
    volumes:
      # Mount your OpenVPN config to connect to the tryhackme network.
      - ./freddiehd.ovpn:/tmp/freddiehd.ovpn

