version: "3"

services:
  kali:
    build:
      context: .
    network_mode: host
    privileged: true
    volumes:
      # Mount your OpenVPN config to connect to the tryhackme network.
      - $OPENVPN_CONFIG_PATH:/tmp/freddiehd.ovpn

